# Makefile.dep created Sat Apr 19 10:39:41 PDT 2014
bigint.o: bigint.cpp bigint.h debug.h
scanner.o: scanner.cpp scanner.h debug.h
debug.o: debug.cpp debug.h util.h
util.o: util.cpp util.h debug.h
main.o: main.cpp bigint.h debug.h iterstack.h scanner.h util.h
